[package]
name = "cli"
version = "0.0.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
hex = "0.4.3"
serde = "1.0.219"
serde_json = "1.0.140"
serde_yaml = "0.9.34"
threshold = { path = "../threshold" }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
