name: Build & Test (CLI)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Format
      run: cargo fmt -- --check
      working-directory: cli
    - name: Clippy
      run: cargo clippy -- -D warnings
      working-directory: cli
    - name: Build
      run: cargo build --verbose
      working-directory: cli
    - name: Test
      run: cargo test --verbose
      working-directory: cli
